package hiforce.pixel.comfy.model.node.prompt.style.extra.picture;

import hiforce.pixel.comfy.model.node.prompt.IPromptType;
import lombok.Getter;

/**
 * @author Rocky Yu
 * @since 2023/11/1
 */
public enum ColorType implements IPromptType {
    ORANGE("orange", "橙色"),
    BLUE("blue", "蓝色"),
    RED("red", "红色"),
    LIGHT_BROWN("light_brown", "浅棕色"),
    DARK_PINK("dark_pink", "深粉色"),
    KHAKI("khaki", "卡其色"),
    BLONDE("blonde", "金黄色的"),
    BROWN("brown", "棕色"),
    BLACK("black", "黑色"),
    GRAY("gray", "灰色"),
    DARKGRAY("darkgray", "深灰色"),
    SILVER("silver", "银色"),
    LIGHTGRAY("lightgray", "浅灰色"),
    GAINSBORO("gainsboro", "庚氏灰色"),
    WHITESMOKE("whitesmoke", "白烟色"),
    SNOW("snow", "雪白色"),
    GHOSTWHITE("ghostwhite", "幽灵白"),
    FLORALWHITE("floralwhite", "花白色"),
    LINEN("linen", "亚麻色"),
    ANTIQUEWHITE("antiquewhite", "古董白"),
    PAPAYAWHIP("papayawhip", "番木瓜色"),
    BLANCHEDALMOND("blanchedalmond", "漂白杏仁色"),
    BISQUE("bisque", "饼干色"),
    MOCCASIN("moccasin", "鹿皮鞋色"),
    NAVAJOWHITE("navajowhite", "纳瓦霍白"),
    PEACHPUFF("peachpuff", "桃肉色"),
    MISTYROSE("mistyrose", "薄雾玫瑰"),
    LAVENDERBLUSH("lavenderblush", "淡紫红色"),
    SEASHELL("seashell", "贝壳白"),
    OLDLACE("oldlace", "老花色"),
    IVORY("ivory", "象牙色"),
    HONEYDEW("honeydew", "蜜色"),
    MINTCREAM("mintcream", "薄荷奶油色"),
    AZURE("azure", "蔚蓝色"),
    ALICEBLUE("aliceblue", "艾莉丝蓝"),
    LAVENDER("lavender", "薰衣草色"),
    LIGHTSTEELBLUE("lightsteelblue", "淡钢蓝色"),
    LIGHTSLATEGRAY("lightslategray", "亮石板灰"),
    SLATEGRAY("slategray", "灰石色"),
    STEELBLUE("steelblue", "钢蓝色"),
    ROYALBLUE("royalblue", "皇家蓝"),
    MIDNIGHTBLUE("midnightblue", "午夜蓝"),
    NAVY("navy", "海军蓝"),
    DARKBLUE("darkblue", "深蓝色"),
    MEDIUMBLUE("mediumblue", "中蓝色"),
    DODGERBLUE("dodgerblue", "道奇蓝"),
    CORNFLOWERBLUE("cornflowerblue", "矢车菊蓝"),
    SKYBLUE("skyblue", "深天蓝"),
    LIGHTBLUE("lightblue", "淡蓝色"),
    POWDERBLUE("powderblue", "粉蓝色"),
    PALETURQUOISE("paleturquoise", "淡青色"),
    LIGHTCYAN("lightcyan", "青色"),
    CYAN("cyan", "碧绿色"),
    AQUAMARINE("aquamarine", "绿松石色"),
    TURQUOISE("turquoise", "中绿松石色"),
    MEDIUMTURQUOISE("mediumturquoise", "深绿松石色"),
    DARKTURQUOISE("darkturquoise", "浅海绿色"),
    LIGHTSEAGREEN("lightseagreen", "军服蓝色"),
    CADETBLUE("cadetblue", "深青色"),
    DARKCYAN("darkcyan", "水鸭色"),
    TEAL("teal", "暗灰蓝色"),
    DARKSLATEGRAY("darkslategray", "深绿色"),
    DARKGREEN("darkgreen", "绿色"),
    GREEN("green", "森林绿色"),
    FORESTGREEN("forestgreen", "海绿色"),
    SEAGREEN("seagreen", "中海绿色"),
    MEDIUMSEAGREEN("mediumseagreen", "中绿宝石色"),
    MEDIUMAQUAMARINE("mediumaquamarine", "暗海绿色"),
    DARKSEAGREEN("darkseagreen", "绿松石色"),
    PALEGREEN("palegreen", "淡绿色"),
    LIGHTGREEN("lightgreen", "草绿色"),
    SPRINGGREEN("springgreen", "中春绿色"),
    MEDIUMSPRINGGREEN("mediumspringgreen", "草坪绿"),
    LAWNGREEN("lawngreen", "查特酒绿色"),
    CHARTREUSE("chartreuse", "黄绿色"),
    GREENYELLOW("greenyellow", "酸橙色"),
    LIME("lime", "酸橙绿"),
    LIMEGREEN("limegreen", "橄榄褐色"),
    YELLOWGREEN("yellowgreen", "橄榄绿色"),
    DARKOLIVEGREEN("darkolivegreen", "橄榄色"),
    OLIVEDRAB("olivedrab", "橄榄褐色"),
    OLIVE("olive", "橄榄色"),
    DARKKHAKI("darkkhaki", "暗卡其色"),
    PALEGOLDENROD("palegoldenrod", "淡金菊色"),
    CORNSILK("cornsilk", "玉米色"),
    BEIGE("beige", "米色"),
    LIGHTYELLOW("lightyellow", "浅黄色"),
    LIGHTGOLDENRODYELLOW("lightgoldenrodyellow", "亮金黄色"),
    LEMONCHIFFON("lemonchiffon", "柠檬绸色"),
    WHEAT("wheat", "小麦色"),
    BURLYWOOD("burlywood", "琥珀色"),
    TAN("tan", "棕褐色"),
    YELLOW("yellow", "黄色"),
    GOLD("gold", "金色"),
    SANDYBROWN("sandybrown", "橙褐色"),
    DARKORANGE("darkorange", "暗橙色"),
    GOLDENROD("goldenrod", "金菊色"),
    PERU("peru", "秘鲁色"),
    DARKGOLDENROD("darkgoldenrod", "暗金菊色"),
    CHOCOLATE("chocolate", "巧克力色"),
    SIENNA("sienna", "黄土赭色"),
    SADDLEBROWN("saddlebrown", "马鞍棕色"),
    MAROON("maroon", "栗色"),
    DARKRED("darkred", "暗红色"),
    FIREBRICK("firebrick", "耐火砖色"),
    INDIANRED("indianred", "印第安红色"),
    ROSYBROWN("rosybrown", "玫瑰棕色"),
    DARKSALMON("darksalmon", "深鲑鱼肉色"),
    LIGHTCORAL("lightcoral", "浅珊瑚色"),
    SALMON("salmon", "鲑鱼肉色"),
    LIGHTSALMON("lightsalmon", "亮鲑鱼肉色"),
    CORAL("coral", "珊瑚色"),
    TOMATO("tomato", "番茄红"),
    ORANGERED("orangered", "橙红色"),
    CRIMSON("crimson", "深粉红色"),
    MEDIUMVIOLETRED("mediumvioletred", "中紫罗兰红色"),
    DEEPPINK("deeppink", "深粉色"),
    HOTPINK("hotpink", "热粉红色"),
    PALEVIOLETRED("palevioletred", "淡紫罗兰红色"),
    PINK("pink", "粉色"),
    LIGHTPINK("lightpink", "浅粉色"),
    THISTLE("thistle", "蓟色"),
    MAGENTA("magenta", "洋红色"),
    FUCHSIA("fuchsia", "紫红色"),
    VIOLET("violet", "紫色"),
    PLUM("plum", "洋李色"),
    ORCHID("orchid", "兰花紫"),
    MEDIUMORCHID("mediumorchid", "中兰花紫色"),
    DARKORCHID("darkorchid", "暗兰花紫色"),
    DARKVIOLET("darkviolet", "暗紫罗兰色"),
    DARKMAGENTA("darkmagenta", "暗洋红色"),
    PURPLE("purple", "紫色"),
    INDIGO("indigo", "靛蓝色"),
    DARKSLATEBLUE("darkslateblue", "暗灰蓝色"),
    BLUEVIOLET("blueviolet", "蓝紫色"),
    MEDIUMPURPLE("mediumpurple", "中紫色"),
    SLATEBLUE("slateblue", "石蓝色"),
    MEDIUMSLATEBLUE("mediumslateblue", "中石板蓝色");
    @Getter
    private final String value;

    @Getter
    private final String valueCn;

    @Getter
    private final String imageUrl = null;

    @Getter
    private final String words;

    ColorType(String value, String valueCn) {
        this.value = value;
        this.valueCn = valueCn;
        this.words = value;
    }
}
