package hiforce.pixel.comfy.model.node.prompt.style.extra.expression;

import hiforce.pixel.comfy.model.node.prompt.IPromptType;
import lombok.Getter;

/**
 * @author Rocky Yu
 * @since 2023/11/1
 */
public enum MovementsType implements IPromptType {
    STANDING("standing", "站立"),
    ON_BACK("on back", "躺"),
    ON_STOMACH("on stomach", "趴"),
    KNEELING("kneeling", "跪"),
    ON_SIDE("on_side", "侧卧"),
    TOP_DOWN_BOTTOM_UP("top-down_bottom-up", "趴着翘臀"),
    THE_POSE("the_pose", "趴在地上并翘起脚"),
    BENT_OVER("bent_over", "翘臀姿势"),
    UPSIDE_DOWN("upside-down", "倒立"),
    REVERSAL("reversal", "反转"),
    FIGHTING_STANCE("fighting_stance", "战斗姿态"),
    LEANING_TO_THE_SIDE("leaning_to_the_side", "靠在一边"),
    LEANING("leaning", "倚靠|身体倾斜"),
    LEANING_BACK("leaning_back", "身体往后靠"),
    LEANING_ON_OBJECT("leaning_on_object", "靠在物体上"),
    ARCHED_BACK("arched_back", "弓身体"),
    LEANING_FORWARD("leaning_forward", "身体前倾"),
    AFLOAT("afloat", "浮(在水上"),
    LYING("lying", "躺着的"),
    FETAL_POSITION("fetal_position", "胎儿姿势(躺)"),
    LYING_ON_PERSON("lying_on_person", "躺在人身上"),
    LYING_ON_THE_LAKE("lying_on_the_lake", "躺在湖面上"),
    LYING_ON_WATER("lying_on_water", "躺在水中"),
    PRONE_BONE("prone_bone", "俯卧后入"),
    RECLINING("reclining", "斜倒斜躺姿势"),
    SLEEPING_UPRIGHT("sleeping_upright", "(不躺着)睡觉|直立睡觉"),
    PRESENTING("presenting", "展示（后接部位）"),
    SPINNING("spinning", "旋转"),
    POSING("posing", "摆姿势"),
    STYLISH_POSE("stylish_pose", "时尚姿势"),
    PUBLIC_INDECENCY("public_indecency", "公然猥亵"),
    PARODY("parody", "模仿"),
    IN_CONTAINER("in_container", "在容器中"),
    AGAINST_GLASS("against_glass", "挤压玻璃(无效)"),
    AIMING("aiming", "瞄准"),
    AIMING_AT_VIEWER("aiming_at_viewer", "瞄准了读者(的视角)"),
    APPLYING_MAKEUP("applying_makeup", "化妆"),
    BATHING("bathing", "洗澡"),
    BITING("biting", "咬"),
    BLEEDING("bleeding", "出血"),
    BLOWING("blowing", "吹"),
    BOWING("bowing", "鞠躬"),
    BREATHING_FIRE("breathing_fire", "喷火"),
    BROOM_RIDING("broom_riding", "骑扫帚"),
    BRUSHING_TEETH("brushing_teeth", "刷牙"),
    BUBBLE_BLOWING("bubble_blowing", "吹泡泡"),
    BULLYING("bullying", "欺负"),
    BURNING("burning", "燃烧"),
    CAST("cast", "投掷"),
    CHASING("chasing", "追逐"),
    CLEANING("cleaning", "打扫"),
    CLIMBING("climbing", "攀爬"),
    COMFORTING("comforting", "安慰"),
    COOKING("cooking", "烹饪"),
    CRYING("crying", "哭"),
    CUDDLING("cuddling", "拥抱"),
    DANCING("dancing", "跳舞"),
    DIVING("diving", "潜水"),
    DRAGGING("dragging", "拖某物"),
    DRAWING("drawing", "绘画"),
    DRAWING_BOW("drawing_bow", "拉弓"),
    DREAMING("dreaming", "做梦"),
    DRINKING("drinking", "喝"),
    DRIVING("driving", "驾驶"),
    DROPPING("dropping", "(意外)掉落"),
    DRYING("drying", "弄干(浴后)"),
    DUAL_WIELDING("dual_wielding", "双持"),
    EXERCISE("exercise", "做运动"),
    FIGHTING("fighting", "战斗中的"),
    FIRING("firing", "射击"),
    FISHING("fishing", "钓鱼"),
    FLAPPING("flapping", "拍打动作"),
    FLASHING("flashing", "露出"),
    FLEEING("fleeing", "在逃跑的"),
    FLEXING("flexing", "秀肌肉"),
    FLYING("flying", "飞行"),
    FLYING_KICK("flying_kick", "飞踢"),
    HAIR_BRUSHING("hair_brushing", "梳头"),
    HAIR_TUCKING("hair_tucking", "撩头发"),
    HANGING("hanging", "吊起来的"),
    HITTING("hitting", "击打"),
    IMAGINING("imagining", "在想象的"),
    JUMPING("jumping", "跳跃"),
    KICKING("kicking", "踢"),
    LICKING("licking", "舔"),
    LICKING_LIPS("licking_lips", "舔嘴唇"),
    LIP_BITING("lip_biting", "咬嘴唇"),
    MEDITATION("meditation", "冥想"),
    PAINTING("painting", "绘画"),
    PAINTING_ACTION("Painting_(Action)", "画画"),
    PLAYING_CARD("playing_card", "扑克牌"),
    PLAYING_GAMES("playing_games", "打游戏"),
    PLAYING_INSTRUMENT("playing_instrument", "演奏乐器"),
    POLE_DANCING("pole_dancing", "钢管舞"),
    PRAYING("praying", "祈祷"),
    PUNCHING("punching", "挥拳"),
    PUSHING("pushing", "推搡"),
    RAILING("railing", "用手扶着"),
    READING("reading", "阅读"),
    RIDING("riding", "骑"),
    RUNNING("running", "奔跑"),
    SEWING("sewing", "缝纫"),
    SHOPPING("shopping", "购物"),
    SHOWERING("showering", "淋浴"),
    SING("sing", "唱歌"),
    SINGING("singing", "唱歌"),
    SLASHING("slashing", "砍"),
    SLEEPING("sleeping", "睡觉"),
    SMELLING("smelling", "闻"),
    SMOKING("smoking", "抽烟"),
    SNEEZING("sneezing", "打喷嚏"),
    SNOWING("snowing", "下雪"),
    SOAKING_FEET("soaking_feet", "泡脚"),
    SOCCER("soccer", "足球运动"),
    SPILLING("spilling", "从容器中倒出液体的动作"),
    SPITTING("spitting", "从嘴里吐出液体的动作"),
    SPLASHING("splashing", "飞溅"),
    STANDING_ON_LIQUID("standing_on_liquid", "站在水上或液体上"),
    STANDING_ON_ONE_LEG("standing_on_one_leg", "单腿站立"),
    STANDING_SPLIT("standing_split", "站立劈叉|站立高抬腿"),
    STEEPLED_FINGERS("steepled_fingers", "指尖抵着指间"),
    STRANGLING("strangling", "绞首"),
    SWEEPING("sweeping", "打扫"),
    SWIMMING("swimming", "游泳"),
    SWING("swing", "摆动"),
    TAIL_WAGGING("tail_wagging", "摇尾巴"),
    TAKING_PICTURE("taking_picture", "拍照|自拍"),
    TALKING("talking", "有台词的"),
    TALKING_ON_PHONE("talking_on_phone", "打电话"),
    TEASING("teasing", "戏弄"),
    THINKING("thinking", "思考"),
    TICKLING("tickling", "挠痒痒"),
    TOILET_USE("toilet_use", "上厕所"),
    TOSSING_("tossing_", "投掷"),
    TRIPPING("tripping", "被绊倒"),
    TROLLING("trolling", "恶搞行为"),
    TWITCHING("twitching", "抽搐"),
    TYING("tying", "打结(动作)"),
    UNSHEATHING("unsheathing", "拔出鞘的"),
    UNTYING("untying", "解开的"),
    UNZIPPING("unzipping", "拉开拉链(动作)"),
    WADING("wading", "涉水"),
    WAKING_UP("waking_up", "醒来"),
    WALKING("walking", "走路"),
    WALKING_ON_LIQUID("walking_on_liquid", "在液体上行走"),
    WASHING("washing", "洗涤"),
    WHISPERING("whispering", "讲悄悄话"),
    WRESTLING("wrestling", "摔角(运动)"),
    WRITING("writing", "写作"),
    YAWNING("yawning", "打哈欠"),
    HIDING("hiding", "躲藏");
    @Getter
    private final String value;

    @Getter
    private final String valueCn;

    @Getter
    private final String imageUrl = null;

    @Getter
    private final String words;

    MovementsType(String value, String valueCn) {
        this.value = value;
        this.valueCn = valueCn;
        this.words = value;
    }
}
